
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nabila
 */
public class NewJFrame extends javax.swing.JFrame implements PropertyListener{

    /**
     * Creates new form NewJFrame
     */
    
    private RegistrationCourseController rcc = new RegistrationCourseController();
    private Course course;
    private int cnt=0, oid;
    private Connection con;
    private Statement stmt;
    private ResultSet rs;


    
    public NewJFrame() {
        initComponents();
        DoConnect();
    }
    
    public void DoConnect( ){
        try{
             String host = "jdbc:derby://localhost:1527/Course Factory";
             String uName = "nabila";
             String uPass = "123456";
             
             con = DriverManager.getConnection( host, uName, uPass );
             stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
             String SQL = "SELECT * FROM COURSE_LIST";
             rs = stmt.executeQuery( SQL );
             
             rs.next();
             String course = rs.getString("Course_ID");
             course_id_text_field.setText(course);
             
        }
        catch ( SQLException err ) {
             System.out.println( err.getMessage( ) );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        new_reg_button = new javax.swing.JButton();
        course_id_text_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        add_course_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        total_button = new javax.swing.JButton();
        total_text = new javax.swing.JTextField();
        tax_button = new javax.swing.JButton();
        tax_text = new javax.swing.JTextField();
        grand_total_button = new javax.swing.JButton();
        grandtotal_text = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        discount_text = new javax.swing.JTextField();
        discount_button = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Details = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        new_reg_button.setText("New Registration");
        new_reg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_reg_buttonActionPerformed(evt);
            }
        });

        course_id_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_id_text_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Course ID");

        add_course_button.setText("Add");
        add_course_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_course_buttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Credit", "Tution/Credit", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        total_button.setText("Total");
        total_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_buttonActionPerformed(evt);
            }
        });

        total_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_textActionPerformed(evt);
            }
        });

        tax_button.setText("Development Fee/ BD TAX");
        tax_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax_buttonActionPerformed(evt);
            }
        });

        tax_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax_textActionPerformed(evt);
            }
        });

        grand_total_button.setText("Grand Total");
        grand_total_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grand_total_buttonActionPerformed(evt);
            }
        });

        grandtotal_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandtotal_textActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic Excellence", "Freedom Fighter", "Best For NSU", "Best For Student" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        discount_button.setText("Discount");
        discount_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discount_buttonActionPerformed(evt);
            }
        });

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Details.setText("Details");
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(new_reg_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(course_id_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_course_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Details)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Previous)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(total_button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tax_button)
                                .addComponent(grand_total_button)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(discount_button))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tax_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(discount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(grandtotal_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 140, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {course_id_text_field, new_reg_button});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {discount_text, grand_total_button, grandtotal_text, jComboBox1, tax_button, tax_text, total_button, total_text});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(new_reg_button)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(course_id_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_course_button)
                    .addComponent(Next)
                    .addComponent(Previous)
                    .addComponent(Details))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_button)
                    .addComponent(total_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax_button)
                    .addComponent(tax_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discount_button)
                    .addComponent(discount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grandtotal_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grand_total_button))
                .addGap(169, 169, 169))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {course_id_text_field, jLabel1, new_reg_button});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {discount_text, grand_total_button, grandtotal_text, jComboBox1, tax_button, tax_text, total_button, total_text});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_reg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_reg_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        cnt = 0;
        rcc = new RegistrationCourseController();
        total_text.setText("0");
        tax_text.setText("0");
        grandtotal_text.setText("0");
        discount_text.setText("0");
        rcc.addListener(this);
        BeepSound beep = new BeepSound(rcc);
    }//GEN-LAST:event_new_reg_buttonActionPerformed

    private void course_id_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_id_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_id_text_fieldActionPerformed

    private void add_course_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_course_buttonActionPerformed
        // TODO add your handling code here:
        //String str = course_id_text_field.getText();
        
        try {
                oid = rs.getInt("ID");
         }
         catch (SQLException err) {
                JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
         }
        rcc.addCourse(oid);
        course = rcc.getCourse();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        cnt = cnt+1;
        String data1 = course.id;
        String data2 = course.title;
        String data3 = Integer.toString(course.credit);
        String data4 = Integer.toString(course.tutionPerCredit);
        String data5 = Integer.toString(course.subTotal);
        
        Object[] row = { data1, data2, data3, data4, data5 };
             
        model.addRow(row);
    }//GEN-LAST:event_add_course_buttonActionPerformed

    private void total_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_buttonActionPerformed
        // TODO add your handling code here:
        total_text.setText(Integer.toString(rcc.getTotal()));
    }//GEN-LAST:event_total_buttonActionPerformed

    private void total_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_textActionPerformed

    private void tax_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax_buttonActionPerformed
        // TODO add your handling code here:
        tax_text.setText(Integer.toString(rcc.getExtraFeeAmount()));
    }//GEN-LAST:event_tax_buttonActionPerformed

    private void tax_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tax_textActionPerformed

    private void grand_total_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grand_total_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grand_total_buttonActionPerformed

    private void grandtotal_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandtotal_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grandtotal_textActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void discount_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discount_buttonActionPerformed
        // TODO add your handling code here:
        String itemText = (String)jComboBox1.getSelectedItem( );
        System.out.println(itemText);
        rcc.calculateDiscount(itemText);
        
        //System.out.println(rcc.getDiscount());
        discount_text.setText(Integer.toString(rcc.getDiscount()));
        //Set grand total
        rcc.publishEvent();
    }//GEN-LAST:event_discount_buttonActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
         try {
                if ( rs.next( ) ) {
                    String course = rs.getString("Course_ID");
                    course_id_text_field.setText(course);
                }
                else {
                  rs.previous( );
                  JOptionPane.showMessageDialog(NewJFrame.this, "End of File");
                }
         }
         catch (SQLException err) {
                JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
         }



    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        // TODO add your handling code here:
        try {
                if ( rs.previous( ) ) {
                    String course = rs.getString("Course_ID");
                    course_id_text_field.setText(course);
                }
                else {
                  rs.previous( );
                  JOptionPane.showMessageDialog(NewJFrame.this, "Start of File");
                }
         }
         catch (SQLException err) {
                JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
         }
    }//GEN-LAST:event_PreviousActionPerformed

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        // TODO add your handling code here:
        try {
                oid = rs.getInt("ID");
         }
         catch (SQLException err) {
                JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
         }
        IManufacturer im = new ManufacturerProxy(oid);
        String str = im.getDetails();
        JOptionPane.showMessageDialog(NewJFrame.this, str);
    }//GEN-LAST:event_DetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Details;
    private javax.swing.JButton Next;
    private javax.swing.JButton Previous;
    private javax.swing.JButton add_course_button;
    private javax.swing.JTextField course_id_text_field;
    private javax.swing.JButton discount_button;
    private javax.swing.JTextField discount_text;
    private javax.swing.JButton grand_total_button;
    private javax.swing.JTextField grandtotal_text;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton new_reg_button;
    private javax.swing.JButton tax_button;
    private javax.swing.JTextField tax_text;
    private javax.swing.JButton total_button;
    private javax.swing.JTextField total_text;
    // End of variables declaration//GEN-END:variables

   @Override
    public void publish() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        int gtot = rcc.getGrandTotal();
        grandtotal_text.setText(Integer.toString(gtot));
    }

}
